orcid-core/src/main/java/org/orcid/core/salesforce/model/Achievement.java
package org.orcid.core.salesforce.model;

import java.io.Serializable;

/**
 * 
 * @author Will Simpson
 *
 */
public class Achievement implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String badgeId;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBadgeId() {
        return badgeId;
    }

    public void setBadgeId(String badgeId) {
        this.badgeId = badgeId;
    }

    @Override
    public String toString() {
        return "Achievement [id=" + id + ", name=" + name + ", badgeId=" + badgeId + "]";
    }

}

orcid-core/src/main/java/org/orcid/core/salesforce/model/Badge.java
package org.orcid.core.salesforce.model;

import java.io.Serializable;

/**
 * 
 * @author Will Simpson
 *
 */
public class Badge implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String publicDescription;
    private Float index;
    private String indexAndName;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPublicDescription() {
        return publicDescription;
    }

    public void setPublicDescription(String publicDescription) {
        this.publicDescription = publicDescription;
    }

    public Float getIndex() {
        return index;
    }

    public void setIndex(Float index) {
        this.index = index;
    }

    public String getIndexAndName() {
        return indexAndName;
    }

    public void setIndexAndName(String indexAndName) {
        this.indexAndName = indexAndName;
    }

    @Override
    public String toString() {
        return "Badge [id=" + id + ", name=" + name + ", publicDescription=" + publicDescription + ", index=" + index + ", indexAndName=" + indexAndName + "]";
    }

}

orcid-core/src/main/java/org/orcid/core/salesforce/model/CommunityType.java
package org.orcid.core.salesforce.model;

/**
 * 
 * @author Will Simpson
 *
 */
public enum CommunityType {

    ASSOCIATION("Association"), FUNDER("Funder"), GOVERNMENT("Government"), OTHER("Other"), PUBLISHER("Publisher"), REPOSITORY("Repository/Profile Org"), RESEARCH_INSTITUTE("Research Institute");

    private final String value;

    CommunityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommunityType fromValue(String v) {
        for (CommunityType c : CommunityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        return null;
    }

}

orcid-core/src/main/java/org/orcid/core/salesforce/model/Consortium.java
package org.orcid.core.salesforce.model;

import java.io.Serializable;
import java.util.List;

/**
 * 
 * @author Will Simpson
 *
 */
public class Consortium implements Serializable {

    private static final long serialVersionUID = 1L;

    private List<Opportunity> opportunities;

    public List<Opportunity> getOpportunities() {
        return opportunities;
    }

    public void setOpportunities(List<Opportunity> opportunities) {
        this.opportunities = opportunities;
    }

    @Override
    public String toString() {
        return "SalesForceConsortium [opportunities=" + opportunities + "]";
    }

}

orcid-core/src/main/java/org/orcid/core/salesforce/model/Contact.java
package org.orcid.core.salesforce.model;

import java.io.Serializable;
import java.util.Collection;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * 
 * @author Will Simpson
 *
 */
public class Contact implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String accountId;
    private String firstName;
    private String lastName;
    private String email;
    private ContactRole role;
    private String orcid;
    private Member member;
    private boolean selfServiceEnabled;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getName() {
        return firstName + " " + lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public ContactRole getRole() {
        return role;
    }

    public void setRole(ContactRole role) {
        this.role = role;
    }

    public boolean isMainContact() {
        return ContactRoleType.MAIN_CONTACT.equals(role);
    }

    public String getOrcid() {
        return orcid;
    }

    public void setOrcid(String orcid) {
        this.orcid = orcid;
    }

    public Member getMember() {
        return member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    public boolean isSelfServiceEnabled() {
        return selfServiceEnabled;
    }

    public void setSelfServiceEnabled(boolean selfServiceEnabled) {
        this.selfServiceEnabled = selfServiceEnabled;
    }

    @Override
    public String toString() {
        return "Contact [id=" + id + ", accountId=" + accountId + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email + ", role=" + role
                + ", orcid=" + orcid + ", selfServiceEnabled=" + selfServiceEnabled + "]";
    }

    public static Map<String, Contact> mapByContactRoleId(Collection<Contact> contacts) {
        return contacts.stream().collect(Collectors.toMap(c -> c.getRole().getId(), Function.identity()));
    }

}

orcid-core/src/main/java/org/orcid/core/salesforce/model/ContactRoleType.java
package org.orcid.core.salesforce.model;

/**
 * 
 * @author Will Simpson
 *
 */
public enum ContactRoleType {
    
    MAIN_CONTACT("Main relationship contact (OFFICIAL)"), TECHNICAL_CONTACT("Technical contact"), INVOICE_CONTACT("Invoice contact"), COMMS_CONTACT(
            "Comms contact"), OTHER_CONTACT("Other contact"), AGREEMENT_SIGNATORY("Agreement signatory (OFFICIAL)");

    private final String value;

    ContactRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContactRoleType fromValue(String v) {
        for (ContactRoleType c : ContactRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        return null;
    }

}

orcid-core/src/main/java/org/orcid/pojo/IdentifierType.java
package org.orcid.pojo;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.orcid.persistence.jpa.entities.ClientDetailsEntity;

@XmlRootElement
public class IdentifierType implements Serializable{

    private static final long serialVersionUID = 1L;
    public static final String PRIMARY_USE_WORK = "work";
    public static final String PRIMARY_USE_FUNDING = "funding";
    
    
    private String name;
    private Long id;
    private String validationRegex;
    private String resolutionPrefix;
    private String description;
    private Date dateCreated;
    private Date lastModified;
    private Boolean caseSensitive;
    private String primaryUse;
    private Boolean deprecated = Boolean.FALSE;    
    
    private ClientDetailsEntity sourceClient;
    
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Long getPutCode() {
        return id;
    }
    public void setPutCode(Long id) {
        this.id = id;
    }
    public String getValidationRegex() {
        return validationRegex;
    }
    @XmlTransient
    public void setValidationRegex(String validationRegex) {
        this.validationRegex = validationRegex;
    }
    public String getResolutionPrefix() {
        return resolutionPrefix;
    }
    public void setResolutionPrefix(String resolutionPrefix) {
        this.resolutionPrefix = resolutionPrefix;
    }
    public Boolean getDeprecated() {
        return deprecated;
    }
    public void setDeprecated(Boolean deprecated) {
        this.deprecated = deprecated;
    }
    public Date getDateCreated() {
        return dateCreated;
    }
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getLastModified() {
        return lastModified;
    }
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
    @XmlTransient
    public ClientDetailsEntity getSourceClient() {
        return sourceClient;
    }
    public void setSourceClient(ClientDetailsEntity sourceClient) {
        this.sourceClient = sourceClient;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getCaseSensitive() {
        return caseSensitive;
    }
    public void setCaseSensitive(Boolean caseSensitive) {
        this.caseSensitive = caseSensitive;
    }
    public String getPrimaryUse() {        
        return primaryUse;
    }
    public void setPrimaryUse(String primaryUse) {
        this.primaryUse = primaryUse;
    }
    @Override
    public String toString() {
        return "IdentifierType [name=" + name + ", id=" + id + ", validationRegex=" + validationRegex + ", resolutionPrefix=" + resolutionPrefix + ", description="
                + description + ", dateCreated=" + dateCreated + ", lastModified=" + lastModified + ", caseSensitive=" + caseSensitive + ", primaryUse=" + primaryUse
                + ", deprecated=" + deprecated + ", sourceClient=" + sourceClient + "]";
    }

}

orcid-core/src/main/java/org/orcid/core/utils/OrcidEhCacheFactoryBean.java
package org.orcid.core.utils;

import java.io.Serializable;
import java.time.Duration;
import java.time.temporal.ChronoUnit;

import org.ehcache.Cache;
import org.ehcache.CacheManager;
import org.ehcache.config.builders.CacheConfigurationBuilder;
import org.ehcache.config.builders.ExpiryPolicyBuilder;
import org.ehcache.config.builders.ResourcePoolsBuilder;
import org.ehcache.config.units.EntryUnit;
import org.ehcache.config.units.MemoryUnit;
import org.ehcache.spi.loaderwriter.CacheLoaderWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.FactoryBean;
import org.springframework.beans.factory.InitializingBean;

/**
 * 
 * @author Will Simpson
 * 
 */
public class OrcidEhCacheFactoryBean implements FactoryBean<Cache<?, ?>>, InitializingBean {

    private static final Logger LOGGER = LoggerFactory.getLogger(OrcidEhCacheFactoryBean.class);

    private CacheManager cacheManager;

    private String cacheName;

    private int maxElementsInMemory = 100;
    
    private int maxMegaBytesInMemory = 0;

    private int timeToIdleSeconds = 60;

    private long maxMegaBytesOnDisk = 0;

    private boolean copyValues = true;

    private CacheLoaderWriter<Serializable, Serializable> cacheLoaderWriter;

    private Cache<?, ?> cache;

    public CacheManager getCacheManager() {
        return cacheManager;
    }

    public void setCacheManager(CacheManager cacheManager) {
        this.cacheManager = cacheManager;
    }

    public String getCacheName() {
        return cacheName;
    }

    public void setCacheName(String cacheName) {
        this.cacheName = cacheName;
    }

    public int getMaxElementsInMemory() {
        return maxElementsInMemory;
    }

    public void setMaxElementsInMemory(int maxElementsInMemory) {
        this.maxElementsInMemory = maxElementsInMemory;
    }

    public int getMaxMegaBytesInMemory() {
        return maxMegaBytesInMemory;
    }

    public void setMaxMegaBytesInMemory(int maxMegaBytesInMemory) {
        this.maxMegaBytesInMemory = maxMegaBytesInMemory;
    }

    public int getTimeToIdleSeconds() {
        return timeToIdleSeconds;
    }

    public void setTimeToIdleSeconds(int timeToIdleSeconds) {
        this.timeToIdleSeconds = timeToIdleSeconds;
    }

    public long getMaxMegaBytesOnDisk() {
        return maxMegaBytesOnDisk;
    }

    public void setMaxMegaBytesOnDisk(long maxMegaBytesOnDisk) {
        this.maxMegaBytesOnDisk = maxMegaBytesOnDisk;
    }

    public boolean isCopyValues() {
        return copyValues;
    }

    public void setCopyValues(boolean copyValues) {
        this.copyValues = copyValues;
    }

    public void setCacheLoaderWriter(CacheLoaderWriter<Serializable, Serializable> cacheLoaderWriter) {
        this.cacheLoaderWriter = cacheLoaderWriter;
    }

    @Override
    public Cache<?, ?> getObject() {
        return this.cache;
    }

    @Override
    public Class<?> getObjectType() {
        return (this.cache != null ? this.cache.getClass() : Cache.class);
    }

    @Override
    public boolean isSingleton() {
        return true;
    }

    @Override
    public void afterPropertiesSet() throws Exception {
        Cache<Serializable, Serializable> existingCache = cacheManager.getCache(cacheName, Serializable.class, Serializable.class);
        if (existingCache == null) {
            ResourcePoolsBuilder resourcePoolsBuilder = ResourcePoolsBuilder.newResourcePoolsBuilder();
            if (this.maxMegaBytesInMemory > 0) {
                resourcePoolsBuilder = resourcePoolsBuilder.heap(maxMegaBytesInMemory, MemoryUnit.MB);
            } else {
                resourcePoolsBuilder = resourcePoolsBuilder.heap(this.maxElementsInMemory, EntryUnit.ENTRIES);
            }
            if (this.maxMegaBytesOnDisk > 0) {
                resourcePoolsBuilder = resourcePoolsBuilder.disk(this.maxMegaBytesOnDisk, MemoryUnit.MB);
            }
            CacheConfigurationBuilder<Serializable, Serializable> cacheConfigurationBuilder = CacheConfigurationBuilder
                    .newCacheConfigurationBuilder(Serializable.class, Serializable.class, resourcePoolsBuilder)
                    .withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.of(this.timeToIdleSeconds, ChronoUnit.SECONDS)));
            if (this.copyValues) {
                cacheConfigurationBuilder = cacheConfigurationBuilder.withValueSerializingCopier();
            }
            if (this.cacheLoaderWriter != null) {
                cacheConfigurationBuilder = cacheConfigurationBuilder.withLoaderWriter(this.cacheLoaderWriter);
            }
            this.cache = cacheManager.createCache(cacheName, cacheConfigurationBuilder.build());
        } else {
            this.cache = existingCache;
        }
    }

}

orcid-core/src/main/java/org/orcid/core/utils/OrcidEhCacheManagerFactoryBean.java
package org.orcid.core.utils;

import java.io.File;

import javax.annotation.Resource;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang3.RandomStringUtils;
import org.ehcache.PersistentCacheManager;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.orcid.core.manager.impl.OrcidUrlManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.FactoryBean;

public class OrcidEhCacheManagerFactoryBean implements FactoryBean<PersistentCacheManager> {

    private static final Logger LOGGER = LoggerFactory.getLogger(OrcidEhCacheManagerFactoryBean.class);
    
    private static final String EHCACHE_DIR_PROPERTY = "org.orcid.ehcache.dir";

    private static PersistentCacheManager persistentCacheManager;

    @Resource
    private OrcidUrlManager orcidUrlManager;

    private String getStoragePath() {
        String ehcacheDir = System.getProperty(EHCACHE_DIR_PROPERTY);
        if(StringUtils.isBlank(ehcacheDir)) {
            String tmpDir = System.getProperty("java.io.tmpdir");
            if (!tmpDir.endsWith(File.separator)) {
                tmpDir += File.separator;
            }
            String randomString = RandomStringUtils.randomAlphanumeric(16);
            ehcacheDir = tmpDir + "ehcache" + File.separator + randomString;
            System.setProperty(EHCACHE_DIR_PROPERTY, ehcacheDir);
        }
        return ehcacheDir + File.separator + orcidUrlManager.getAppName() + File.separator + "programmatic";
    }

    @Override
    public PersistentCacheManager getObject() throws Exception {
        if (persistentCacheManager == null) {
            String storagePath = getStoragePath();
            LOGGER.info("Cache manager dir: {}", storagePath);
            persistentCacheManager = CacheManagerBuilder.newCacheManagerBuilder().with(CacheManagerBuilder.persistence(storagePath)).build(true);
        }
        return persistentCacheManager;
    }

    @Override
    public Class<?> getObjectType() {
        return PersistentCacheManager.class;
    }

    @Override
    public boolean isSingleton() {
        return true;
    }

}

orcid-core/src/main/resources/org/orcid/core/template/digest_email_html.ftl
<#import "email_macros.ftl" as emailMacros />
<#escape x as x?html>
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <div style="padding: 20px; padding-top: 0px; font-family: arial, helvetica, sans-serif; font-size: 15px; color: #494A4C; width: 800px;">
            <img src="https://orcid.org/sites/all/themes/orcid/img/orcid-logo.png" alt="ORCID.org"/>
            <hr />
            <span style="font-weight: bold;">
                <@emailMacros.msg "email.common.hi" /><@emailMacros.space />${emailName}<@emailMacros.msg "email.common.dear.comma" />
            </span>
            <p>
                <@emailMacros.msg "email.digest.youhave" /><@emailMacros.space />${totalMessageCount}<@emailMacros.space /><@emailMacros.msg "email.digest.new" /><@emailMacros.space /><#if ((totalMessageCount?number) == 1)><@emailMacros.msg "email.digest.notification" /><#else><@emailMacros.msg "email.digest.notifications" /></#if><@emailMacros.space /><@emailMacros.msg "email.digest.inyourinbox" /><@emailMacros.space /><@emailMacros.msg "email.digest.pleasevisit_1" /><@emailMacros.space /><a href="${baseUri}/inbox?lang=${locale}" style="color: #338caf; text-decoration: none;"><@emailMacros.msg "email.digest.orcidinbox" /></a><@emailMacros.space /><@emailMacros.msg "email.digest.pleasevisit_4" />
            </p>
            <#if digestEmail.notificationsBySourceId['ORCID']??> 
            <p>
                <#-- Use assign to prevent strange whitespace formatting in output -->
                <#assign orcidwouldlikeyoutoknow><@emailMacros.msg "email.digest.orcidwouldlikeyoutoknow" /></#assign>
                ${orcidwouldlikeyoutoknow}
                <ul>
                <#list digestEmail.notificationsBySourceId['ORCID'].allNotifications as notification>
                    <li>${notification.subject}</li>
                </#list>
                </ul>
            </p>
            </#if>
            <#list digestEmail.notificationsBySourceId?keys?sort as sourceId>
	        <#if sourceId != 'ORCID'>
		    <#list digestEmail.notificationsBySourceId[sourceId].notificationsByType?keys?sort as notificationType>
			<#list digestEmail.notificationsBySourceId[sourceId].notificationsByType[notificationType] as notification>
			<#if notificationType == 'PERMISSION'>
            <p>
                <div><img src="https://orcid.org/sites/all/themes/orcid/img/request.png">&nbsp;${(digestEmail.notificationsBySourceId[sourceId].source.sourceName.content)!sourceId}: <#if notification.notificationSubject??>${notification.notificationSubject} <#if notification.createdDate??>(${notification.createdDate.year?c}-<#if notification.createdDate.month?string?length == 1>0${notification.createdDate.month?c}<#else>${notification.createdDate.month?c}</#if>-<#if notification.createdDate.day?string?length == 1>0${notification.createdDate.day?c}<#else>${notification.createdDate.day?c}</#if>)</#if> <#else><@emailMacros.msg "email.digest.requesttoadd" /> <#if notification.createdDate??>(${notification.createdDate.year?c}-<#if notification.createdDate.month?string?length == 1>0${notification.createdDate.month?c}<#else>${notification.createdDate.month?c}</#if>-<#if notification.createdDate.day?string?length == 1>0${notification.createdDate.day?c}<#else>${notification.createdDate.day?c}</#if>)</#if> </#if></div>
                <#assign itemsByType=notification.items.itemsByType>
                <#list itemsByType?keys?sort as itemType>
                <table width="100%" style="font-family: arial, helvetica, sans-serif; padding-left: 20px; padding-top: 15px;">
					<thead>
						<tr>
							<td width="100%" style="padding: 5px 0 5px 10px; color: #FFF;background: #939598; font-weight: bold; font-size: 18px;">					                
               					<img src="https://orcid.org/sites/all/themes/orcid/img/chevron-down.png">&nbsp;<@emailMacros.msg "email.common.recordsection." + itemType /> (${itemsByType[itemType]?size})
               				</td>
               			</tr>
               		</thead>
               		<tbody>
               			<#list itemsByType[itemType] as item>
               			<tr>
               				<td width="100%" style="padding-top: 15px; padding-bottom: 10px; font-weight: bold; color: #494A4C">
               					${item.itemName?trim} <#if item.externalIdentifier??>(<span style="color: #338caf; font-weight: normal;">${item.externalIdentifier.type?lower_case}:</span> <#if item.externalIdentifier.value?starts_with("http")><a href="${item.externalIdentifier.value}" style="color: #338caf; font-weight: normal; text-decoration: none;">${item.externalIdentifier.value}</a><#else><span style="color: #338caf; font-weight: normal;">${item.externalIdentifier.value}</span></#if>)</#if>			
               				</td>
               			</tr>
                		</#list>
		                <tr>
							<td width="100%">
								<ul style="padding: 0; margin: 0; float: right;">
									<li style="display: inline;">						                
			                			<a href="${baseUri}/inbox#${notification.putCode}" style="padding: 10px 15px; float: left; color: #338caf; text-decoration: none;">more info...</a>
			                		</li>
			                		<li style="display: inline;">
			               				<a href="${baseUri}/inbox/encrypted/${notification.encryptedPutCode}/action" style="padding: 10px 15px; background: #338caf; color: #FFF; text-decoration: none; float: right;"><@emailMacros.msg "email.digest.addnow" /></a> 
		                			</li>
		                		</ul>
		                	</td>
		                </tr>
                    </tbody>					                      
	        	</table>
	        	</#list> 
            </p>
			<#elseif notificationType == 'AMENDED'>
            <p>
                <#assign amendedSection><@emailMacros.msg "email.common.recordsection." + notification.amendedSection /></#assign>
                <div>
                    <img src="https://orcid.org/sites/all/themes/orcid/img/update.png">&nbsp;<@emailMacros.msg "email.digest.hasupdated_1" />
                    ${(digestEmail.notificationsBySourceId[sourceId].source.sourceName.content)!sourceId}<@emailMacros.space /><@emailMacros.msg "email.digest.hasupdated_2" /><@emailMacros.space />${amendedSection?lower_case}<@emailMacros.space /><@emailMacros.msg "email.digest.hasupdated_3" /><#if notification.createdDate??>(${notification.createdDate.year?c}-<#if notification.createdDate.month?string?length == 1>0${notification.createdDate.month?c}<#else>${notification.createdDate.month?c}</#if>-<#if notification.createdDate.day?string?length == 1>0${notification.createdDate.day?c}<#else>${notification.createdDate.day?c}</#if>)</#if>
                </div>
                <#if notification.items??>
                <ul>
                <#list notification.items.items as item>
                    <li>${item.itemName} <#if item.externalIdentifier??>(${item.externalIdentifier.type?lower_case}: ${item.externalIdentifier.value})</#if></li>
                </#list>
                </ul>
                </#if>
            </p>
            <#elseif notificationType == 'INSTITUTIONAL_CONNECTION'>
            <p> 
            	<div><img src="https://orcid.org/sites/all/themes/orcid/img/request.png">&nbsp;<@emailMacros.msg 'email.institutional_connection.1' /><@emailMacros.space />${(notification.idpName)!}<@emailMacros.space /><@emailMacros.msg 'email.institutional_connection.2' /><a href="${baseUri}/inbox/encrypted/${notification.encryptedPutCode}/action"><@emailMacros.msg "email.institutional_connection.here" /></a><@emailMacros.msg 'email.institutional_connection.3' /><@emailMacros.space />${(notification.source.sourceName.content)!sourceId}<@emailMacros.space /><@emailMacros.msg 'email.institutional_connection.4' /><@emailMacros.space /><#if notification.createdDate??>(${notification.createdDate.year?c}-<#if notification.createdDate.month?string?length == 1>0${notification.createdDate.month?c}<#else>${notification.createdDate.month?c}</#if>-<#if notification.createdDate.day?string?length == 1>0${notification.createdDate.day?c}<#else>${notification.createdDate.day?c}</#if>)</#if></div>
            </p>
            <#else>
            <p>
            	<div><img src="https://orcid.org/sites/all/themes/orcid/img/request.png">&nbsp;${(notification.subject)}</div>
            </p>
            </#if>
			</#list>
			</#list>
			</#if>
            </#list>
            <p style="text-align: center;">
                <a href="${baseUri}/inbox?lang=${locale}" style="text-decoration: none; color: #338caf;">                    
                     <!-- Use assign to prevent strange whitespace formatting in output -->
                     <#assign viewyourinbox><@emailMacros.msg "email.digest.viewyourinbox" /></#assign>
                     ${viewyourinbox}                    
                </a>
            </p>
            <p>                
                <@emailMacros.msg "email.digest.youhavereceived_1" /><@emailMacros.space /><@emailMacros.msg "email.digest.youhavereceived_2" /><@emailMacros.space /><a href="<@emailMacros.msg "email.digest.learnmorelink" />" style="color: #338caf; text-decoration: none;"><@emailMacros.msg "email.digest.learnmore" /></a>
            </p>
            <p>
                <@emailMacros.msg "email.digest.youmayadjust_1" /><@emailMacros.space /><a href="${baseUri}/account?lang=${locale}" style="color: #338caf; text-decoration: none;"><@emailMacros.msg "email.digest.accountsettings" /></a>.
            </p>
            <hr />
            <p>
               <#include "email_footer_html.ftl"/>
            </p>
        </div>      
    </body>
</html>
</#escape>

orcid-core/src/main/resources/org/orcid/core/template/reactivation_email.ftl
<#import "email_macros.ftl" as emailMacros />

<@emailMacros.msg "email.reactivation.thank_you" />

<@emailMacros.msg "email.reactivation.to_reactivate" />

${reactivationUrl}

<@emailMacros.msg "email.reactivation.after" />

<@emailMacros.msg "email.common.if_you_have_any1" /> <@emailMacros.msg "email.common.need_help.description.2.href" /><@emailMacros.msg "email.common.if_you_have_any2" />

<@emailMacros.msg "email.common.warm_regards" />
<@emailMacros.msg "email.common.need_help.description.2.href" />


${baseUri}/home?lang=${locale}

<@emailMacros.msg "email.common.you_have_received_this_email" />
<#include "email_footer.ftl"/>